Redis:
  scale: 1
  health_check:
    port: 6370
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    healthy_threshold: 2
    response_timeout: 2000
Mailserver:
  scale: 1
Discourse:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000
PostgresSQL:
  scale: 1
  health_check:
    port: 5432
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    healthy_threshold: 2
    response_timeout: 2000
