.catalog
  name: Mailserver
  description: Mailserver based on Postfix 3, Amavisd-NG
  version: 3.1.0
  uuid: mailserver-server-0
  questions:
  - variable: DOMAIN
    label: Domain
    description: Primary Domain
    type: string
    default: example.com
  - variable: SSL_CERTIFICATE
    label: Certificate
    description: SSL Certificate (PEM-encoded)
    type: multiline
  - variable: SSL_CERTIFICATE_KEY
    label: Private Key
    description: SSL Private Key (PEM-encoded)
    type: multiline
  - variable: SSL_CERTIFICATE_CHAIN
    label: Certificate Chain
    description: SSL Certificate Chain (PEM-encoded)
    type: multiline
  - variable: DATABASE_DRIVER
    label: Database Type
    description: Database Type
    type: enum
    default: mysql
    options:
    - mysql
    - postgres
    - sqlite3
  - variable: DATABASE_HOST
    label: Database Server
    description: Database Server
    type: service
  - variable: DATABASE_USER
    label: Database Username
    description: Database Username
    type: string
    default: postfix
  - variable: DATABASE_PASSWORD
    label: Database Password
    description: Database Password
    type: password
  - variable: DATABASE_NAME
    label: Database Name
    description: Database Name
    type: string
    default: postfix
  - variable: PROXY_PROTOCOL_ENABLE
    label: Enable Proxy-Protocol
    description: Enable Proxy-Protocol
    type: boolean
    default: false
  - variable: PROXY_PROTOCOL_OFFSET
    label: Offset
    description: Offset of proxied services
    type: int
    default: 20000

Server:
  scale: 1
  health_check:
    port: 25
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    healthy_threshold: 2
  metadata:
    gr.stei.mailserver.domain: ${DOMAIN}
    gr.stei.mailserver.global.ssl.certificate: ${SSL_CERTIFICATE}
    gr.stei.mailserver.global.ssl.key: ${SSL_CERTIFICATE_KEY}
    gr.stei.mailserver.global.ssl.chain: ${SSL_CERTIFICATE_CHAIN}
    gr.stei.mailserver.database.driver: ${DATABASE_DRIVER}
    gr.stei.mailserver.database.server: ${DATABASE_HOST}
    gr.stei.mailserver.database.user: ${DATABASE_USER}
    gr.stei.mailserver.database.password: ${DATABASE_PASSWORD}
    gr.stei.mailserver.database.name: ${DATABASE_NAME}
    gr.stei.mailserver.proxy.enable: ${PROXY_PROTOCOL_ENABLE}
    gr.stei.mailserver.proxy.offset: ${PROXY_PROTOCOL_OFFSET}
